### DISCUSSION TITLE
Usage with a cross toolchain

### DISCUSSION THREAD

**Discussion by tgross35** [gungraun/gungraun#345] [Q&A]
Are there any recommended workflow for using iai-callgrind to run benchmarks with qemu? I have gotten pretty far by copying this repo's `docker/` and `Cross.toml` and adding a step to install `iai-callgrind-runner`, but various permutations seem to give me some different errors (e.g. can't locate iai-callgrind-runner or exec format errors running it).

**Comment by gamma0987** [comment]
Setting up docker/cross is tricky but I think all that's needed is in the `docker/*` and `Cross.toml` files of this repo you've already found. Alone from your description, I can't tell for sure what is going wrong in your case. An exec format error indicates that you're running a binary iai-callgrind-runner or valgrind with the wrong build/os. For example valgrind needs to be baked into the qemu image and it's not sufficient to install it into the docker image. I'm going to make this kind of setup easier but this'll take time I don't have currrently.

**Comment by gamma0987** [comment]
@tgross35 The situation has improved a lot since the last time I wrote and running gungraun with docker/cross is simpler now. I created an image-based fork https://github.com/gungraun/cross-valgrind of the cross-rs project with images that can run Valgrind. The project is still in alpha state but I was able to use the images for the tests of the `valgrind-requests` package without issues. Feel free to experiment with these images. If you have suggestions for improvement, I'm happy to hear about them. Here's a short usage example with the s390x target and the most recent gungraun version and `cross-valgrind` image. The content of the `Cross.toml`:

```toml
# Cross.toml
[target.s390x-unknown-linux-gnu]
runner = "qemu-user"
# :latest tag is also available but during alpha it's maybe best to pin it to a specific version
image = "ghcr.io/gungraun/s390x-unknown-linux-gnu:3.27.0-alpha.2"
pre-build = [
    # Minimum is v0.18.0 but I recommend at least v0.19.0
    "curl -fsSL https://github.com/gungraun/gungraun/releases/download/v0.19.0/gungraun-runner-v0.19.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C /tmp --strip-components=1",
]

[target.s390x-unknown-linux-gnu.env]
passthrough = [
    "GUNGRAUN_RUNNER=/tmp/gungraun-runner",
    "GUNGRAUN_VALGRIND_RUNNER=/linux-runner",
    "GUNGRAUN_VALGRIND_RUNNER_ARGS=s390x",
    # gungraun-runner clears the original environment variables and TMPDIR needs to be passed
    # through (at the moment) to avoid errors in the /linux-runner script
    "GUNGRAUN_ENVS=CROSS_RUNNER=qemu-system TMPDIR",
]
```

I tested it with `cross +nightly bench -p builtins-test --bench mem_icount --features icount --target s390x-unknown-linux-gnu` (official cross v0.2.5 not from my fork) in the compiler-builtins repo on the main branch without problems. The flow is roughly like this:

cross
-> docker
-> s390x benchmark build
-> run s390x benchmark binary via /linux-runner with qemu-user once
-> calls x86_64 gungraun-runner
-> runs s390x valgrind and benchmark via /linux-runner with qemu-system for every benchmark case
